AWSTemplateFormatVersion: 2010-09-09
Description: Cloud formation template for EC2 Instance with Security Group
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair for SSH
    Default: 'my-key-pair'
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium]

Resources:
    
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0552e3455b9bc8d50
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      InstanceType: !Ref InstanceType

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'My Security Group'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 